function display(){
 console.log("my sir name:mohit");
 console.log("my name is: sharma");
}
display();
function showDetails(myName){

}
showDetails();

function swapvalues(value1,value2,you,me){
 console.log("before swap",value1,value2);
 var temp=value1
 value1=temp
 console.log("after swap",value1,value2);
}

swapvalues(100,200);
swapvalues(2,4);
swapvalues("you,me");
swapvalues();
console.log("function with argument and return value");
function rajubhaiya(paisa){
 console.log("going in ",paisa);
 console.log("purchased fresh vegetables",paisa);
 console.log("come back");
 return "bag of vegetables",paisa;
 
 
}
var bagofvegetables=rajubhaiya(100);
console.log(bagofvegetables);



